name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clean up existing containers
        run: |
          docker ps -aq --filter "name=cicd-pipeline-container" | xargs -r docker rm -f

      - name: Pull and Run Docker Container
        run: |
          docker run -d -p 8080:8080 --pull always --name cicd-pipeline-container \
          wimukthibandara/cicd-pipeline:latest

      - name: Health Check
        run: |
          sleep 10
          curl -f http://localhost:8080 || (echo "Health check failed" && exit 1)
